.nh
.TH mysql_backup.sh 1 "May 2025" mysql_backup.sh "User Manual"
.SH NAME
.PP
mysql_backup.sh - backup MySQL database on Kiwi or Finch to a file

.SH SYNOPSIS
.PP
mysql_backup.sh \fIdb\fP \fIhost\fP

.SH DESCRIPTION
.PP
This program takes two arguments, the first (\fIdb\fP) specifies the MySQL database to be backed up and the second (\fIhost\fP) specifies the host on which the database is located. The resulting file is written to \fI/xnat/san/backups\fP on mrc-swan01.ad.ucl.ac.uk

.SH ENVIRONMENT
.PP
The user must have setup valid credentials in the file \fI~/.mylogin.cnf\fP using the MySQL utility mysql-config-editor.

.PP
The resulting file can be used to restore the database using the \fImysql\fP client.

.SH AUTHOR
.PP
Phil Curran

.SH COPYRIGHT
.PP
All copyright is reserved by the authors.  This software is released under the GPL version 3 software license.

.SH SEE ALSO
.PP
mysql(1), mysqldump(1)
