# Properties File for Swift/Skylark mrc.db package
# CTU IT Support have created a DBA account for use by LHA with limited privileges on the Pegasus instance.
username=DBA
password=!$75R<k19>
hostname=localhost
vendor=mysql
port=3306
# Instances of SWIFT can run in parallel. Rename this to the current database instance.
instance=robin
# Remember passwords were encoded with faulty mechanism in SWFT18 and previous versions have to use robin