# Authors: Phil Curran, SST
# All software released under GNU GPL
# This file is <App Name>/src/mrc/wdap/user/system.properties
# Deployment Environment
# Note that installRoot is the context path not the physical file location, beware!!
#
# Whatever you do, DO NOT PUT QUOTES round the file paths documentDir, etc.!!!!!
#
installServer=mrc-finch01.ad.ucl.ac.uk
installRoot=Condor
dsgMyDBase=robin
#dsgTrolleyLimit=3 # Not Used
dsgBasketLimit=300 
# Database Parameters for MySQL and PostgreSQL
pyMyDriver={MySQL ODBC 5.3 Unicode Driver}; # Not Used
pyMyServer=localhost # Not Used
pyMyDBase=robin 
pyMyUID=DBA 
pyMyPwd=!$75R<k19> 

