# Authors: Phil Curran, SST
# Copyright (c) 2007-2018 UCL/Medical Research Council 
# ALL RIGHTS RESERVED
# This file is Skylark/src/mrc/wdap/user/system.properties
# Deployment Environment
# Note that installRoot is the context path not the physical file location, beware!!
installRoot=Skylark/robin
documentDir=webapps/Skylark/robin/Documents
downloadDir=webapps/Skylark/robin/download
uploadDir=webapps/Skylark/robin/upload
pdfDir=webapps/Skylark/robin/PDF
templateDir=webapps/Skylark/templates
