#+TITLE: Transforming HoC Census and other CSV files between Long/Wide Format
#+AUTHOR: Philip Curran
#+EMAIL: philip.curran AT gmail DOT com
#+LANGUAGE:  en
#+STARTUP: overview
#+TODO: NEXT(n) TODO(t) IN-PROGRESS(i) PROJECT(p) |  DONE(d!) CANCELLED(c!)

#+TAGS: { work(w) home(h) } background(b)
#+TAGS: @philc(p)
* Using Python program long_to_wide

The purpose of this package is to perform transformations of CSV files
between so-called long and wide format. This package was originally
created to transform long format CSV files into wide format for
uploading into the Postgres database **genelects**.

** Long to Wide Transformations

In some of the UK Census data there are long format files which have a
structure similar to this basic outline:

#+BEGIN_SOURCE
id, city, housing_type, pcent_of_total
1, "London", "Private Rented", 20
1, "London", "Owned", 30
1, "London", "Social Housing", 50
2, "Watford", "Private Rented", 15
2, "Watford", "Owned", 35
2, "Watford", "Social Housing", 50
...
#+END_SOURCE

In this example the values in columns 'housing_type' and
'pcent_of_total' are functionally dependent on one another; i.e. the
interpretation of this data is that for each city identified by the
first column (and labelled by the second), the percentage of each
housing type listed in the third column can be read from the
corresponding value of the fourth column in the same row.

This package is intended to take examples like this with functionally
dependent columns in long format and produce a corresponding wide
format version somewhat like this:

#+BEGIN_SOURCE
id, city, private_rented, owned, social_housing
1, "London", 20, 30, 50
2, "Watford", 15, 35, 50
...
#+END_SOURCE

The package requires a configuration file in order to carry out this task.  It needs to specify:
- the primary key or main identifier to be used detect when a //wide// row has been completed
- give the package guidance on how to name the new //wide// columns

This is the task of the YAML configuration file.

** Wide to Long Transformations

By way of contrast, it is often required to take //wide// format files and transform them to long.  One example is the typical use of wide format files containing timings for events that are preated during the day. 

The following is an example from the CrowdED application:

#+BEGIN_SOURCE
date, child_id, call_time, morning_break_start, morning_break_end, lunch_start, lunch_end, late_break_start, late_break_end
27.11.25, 1, 08:00, 10:30, 10:45, 12:30, 13:45, 15:45, 16:00
27.11.25, 2, 08:00, 10:30, 10:45, 12:30, 13:45, 15:45, 16:00
27.11.25, 3, 08:00, 10:30, 10:45, 12:30, 13:45, 15:45, 16:00
27.11.25, 4, 08:00, 10:30, 10:45, 12:30, 13:45, 15:45, 16:00
27.11.25, 5, 08:00, 10:30, 10:45, 12:30, 13:45, 15:45, 16:00
27.11.25, 6, 08:00, 9:15, 9:30, 12:30, 13:45, 15:45, 16:00
27.11.25, 7, 08:00, 9:15, 9:30, 12:30, 13:45, 15:45, 16:00
27.11.25, 8, 08:00, 9:15, 9:30, 12:30, 13:45, 15:45, 16:00
27.11.25, 9, 08:00, 9:15, 9:30, 12:30, 13:45, 15:45, 16:00
27.11.25, 10, 08:00, 9:15, 9:30, 12:30, 13:45, 15:45, 16:00
...
#+END_SOURCE

In order to be able to load these into the //breaks// table of the
CrowdED application, the format required is like this:

#+BETIN_SOURCE
date, child_id, call_time, break_start, break_end
27.11.25, 1, 08:00, 10:30, 10:45
27.11.25, 1, 08:00, 12:30, 13:45
27.11.25, 1, 08:00, 15:45, 16:00
27.11.25, 2, 08:00, 10:30, 10:45
27.11.25, 2, 08:00, 12:30, 13:45
27.11.25, 2, 08:00, 15:45, 16:00
...
#+END_SOURCE

** Common Features of Transformations

As can be seen from the previous long-to-wide example, transformations require the definition of a number of different types of columns in the input CSV file.  They are:

- A primary key or case identifier
- Static columns that are just copied across from input to output CSV files
- Dynamic columns that will be transformed in one of two ways:
  + In Long to Wide transformations
    * One row is created in the output table for every uniquely
      identified case
    * Static columns are copied across to the output table
    * Extra columns are created corresponding to the values of the
      functionally determining column in the table
    * The values of these columns are given by the functionally
      determined column in the table
  + In Wide to Long transformations
    * Several rows are created in the output table, thus the case
      identifier no longer uniquely identifies each row of the output
      table.
    * Static columns are copied across to the output table
    * Each row in the output table is composed of the case identifier,
      any static columns, and a new composite column with values taken
      from one of the dynamic columns
      
** YAML file transform.json

One of these has to be produced for each original CSV file to be
transformed.  It should also be on the search path for Python.

The general structure of the JSON configuration file is as follows:

#+BEGIN_SRC json
  { "input" : "/path/to/long/format/source/csv/file",
    "output" : "/path/to/wide/format/target/file/",
    "primary_key" : "<identifier field in source>",
    "direction": "long | wide",
    "static_cols" : ["<list of colums to appear in target>"],
    "transform_cols" : [
  	{ "long_column" : "<input_fieldA>",
  	  "long_values" : "<output_fieldB>" },
  	{ "long_column" : "<input_fieldC>",
  	  "long_values" : "<output_fieldD>"}
  	...
  	OR
          { "wide_column" : "<output_fieldA>",
  	  "wide_values" : ["<list of input table fields>"]},
          { "wide_column" : "<output_fieldB>",
  	  "wide_values" : ["<list of input table fields>"]},
  	...
  	}
    ]
  }
#+END_SRC

Here is an example JSON configuration file:

#+INCLUDE "transform.json" src json

The //primary_key// field must appear in the list of //static_cols//
shown above.  The //transform_cols// list of pairs of field names
indicate the names of fields which are in long format, i.e. whose
values will become new columns in the resulting target file, together
with the field to be used to provide the value for that new column.
The list of pairs can be repeated as many times as required by the
format of the original CSV source file.

** Using this package
There are two components to successfully using this program:

    - Create a YAML configuration file with the information about the
      input and resulting output CSV files and information about the
      fields within the file which are to be transformed from row
      format to column format.

   - Run the program //long_to_wide.py// with a suitable Python
     virtualenv.  The environment must have the Python packge Pandas
     installed and have the Python module //transform.py// in the
     Python path.

** A Quick Example

The household tenure data is a long file (an excerpt is shown below)
with the field //variables// containing the names of properties and
the two fields //Con_num// and //Con_pc// containing the values that
relate to those properties.

#+BEGIN_SRC
$ csvlook --max-rows 20 /nfs/workspace/ge_data/census/household_tenure/household_tenure_const.csv
| cid       | cname               | regid     | regname       | variables                          | groups          | con_num | con_pc |  rn_pc | nat_pc |
| --------- | ------------------- | --------- | ------------- | ---------------------------------- | --------------- | ------- | ------ | ------ | ------ |
| E14001063 | Aldershot           | E12000008 | South East    | Owns outright                      | Home owners     |  12,789 | 0.277… | 0.343… | 0.330… |
| E14001063 | Aldershot           | E12000008 | South East    | Owns with a mortgage or loan       | Home owners     |  16,373 | 0.355… | 0.314… | 0.287… |
| E14001063 | Aldershot           | E12000008 | South East    | Shared ownership                   | Other           |     806 | 0.017… | 0.014… | 0.009… |
| E14001063 | Aldershot           | E12000008 | South East    | All social landlords               | Social renters  |   6,958 | 0.151… | 0.136… | 0.175… |
| E14001063 | Aldershot           | E12000008 | South East    | Private landlord or letting agency | Private renters |   7,159 | 0.155… | 0.169… | 0.175… |
| E14001063 | Aldershot           | E12000008 | South East    | Other private rented               | Private renters |   2,056 | 0.045… | 0.023… | 0.021… |
| E14001063 | Aldershot           | E12000008 | South East    | Lives rent free                    | Other           |      32 | 0.001… | 0.001… | 0.003… |
| E14001064 | Aldridge-Brownhills | E12000005 | West Midlands | Owns outright                      | Home owners     |  16,458 | 0.420… | 0.344… | 0.330… |
| E14001064 | Aldridge-Brownhills | E12000005 | West Midlands | Owns with a mortgage or loan       | Home owners     |  13,012 | 0.332… | 0.284… | 0.287… |
| E14001064 | Aldridge-Brownhills | E12000005 | West Midlands | Shared ownership                   | Other           |     220 | 0.006… | 0.008… | 0.009… |
#+END_SRC

There are ten columns in this example file:

#+begin_src
  1: cid         # ONS Constituency ID
  2: cname       # Constituency Name
  3: regid       # ONS Region ID
  4: regname     # Region Name
  5: variables   # Type of housing tenure
  6: groups      # Broad housing type
  7: con_num     # Raw count in constituency
  8: con_pc      # Percentage of type within constituency
  9: rn_pc       # Percentage of type within region
 10: nat_pc      # Percentage of type nationally
#+end_src


What would be desirable would be to have a wide format file with
fields for each of the categories contained in //variables// for both
the raw numbers in the constituency (in field //con_num//) and the
percentage within the constituency (in field //con_pc//). The regional
and national percentages are for comparison purposes.

We would like the result of the transformation to look like this:

#+begin_src
  1: cid         # ONS Constituency ID - Primary Key
  2: cname       # Constituency Name 
  3: regid       # ONS Region ID
  4: regname     # Region Name
  5: owns_out_n      # Count of Owns outright in Constituency
  5: owns_out_p      # Pcent of Owns outright in Constituency
  6: owns_mort_n     # Count of Owns with mortgage in Constituency
  6: owns_mort_p     # Pcent of Owns with mortgage in Constituency
  7: owns_shared_n   #
  7: owns_shared_p   #
  8: rent_social_n   #
  8: rent_social_p   #
  9: rent_private_n  #
  9: rent_private_p  #
 10: rent_other_n    #
 10: rent_other_p    #
 11: rent_free_n     #
 11: rent_free_p     # 
 12: groups      # Broad housing type
  9: rn_pc       # Percentage of type within region
 10: nat_pc      # Percentage of type nationally
#+end_src


We can achieve this by first creating a JSON configuration file like this:

#+BEGIN_SRC json
{ "input" : "Household_Tenure.CSV",
  "output" : "Household_Tenure_Wide.CSV",
  "primary_key" : "cid",
  "static_cols" : [ "cname", "regid", "regname", "groups", "rn_pc", "nat_pc" ],
  "transform_cols" : [
      { "long_column" : "variables",
        "long_values" : "con_num" },
      { "long_column" : "variables",
        "long_values" : "con_pc" }
  ]
}
#+END_SRC

The input and output files are specified in the first two entries.
The //primary_key// entry specifies how resulting DataFrames will be
merged together based on the value of this field.


The //static_cols// key lists all the existing fields to be including
in the resulting output file that are already in wide format.  **Note
that this list must include the //primary_key// field.**


Lastly, the //transform_cols// key provides a list of pairs of field
names, the first of which identifies the field which contains the
values that will be used to provide new column names in the output
file, and the second identifies the field which contains the values to
be used for these new column entries.  In the case above, there are
new wide columns to be provided for both constituency raw numbers and
the constituency percentage of the uk population for the categories
contained in the //variables// field.

Running the program is very simply a matter of executing
//long_to_wide.py// with a suitable Python runtime system.

The end result looks like the listing below.  Some column names have
been changed from the default column names generated by the Pandas
merge function.


#+BEGIN_SRC
#+END_SRC


** Where is //long_to_wide.py//

The Python source is located in a directory on **donkey.local**.  You
can access it in either of the following two ways:

    - as "/nfs/workspace/CommonBirds/local/python/reuse/dataman/" if
      you are running Ubuntu inside a Windows WSL environment;
    -- as
       "/home/Public/workspace/CommonBirds/local/python/reuse/dataman/"
       if you are already logged into donkey.local (e.g. via ssh).

Please improve it!
