/*
    This file is part of Jay/Condor/Swift.

    Jay/Condor/Swift is free software: you can redistribute it and/or
    modify it under the terms of the GNU General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    Jay/Condor/Swift is distributed in the hope that it will be
    useful, but WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
    PURPOSE. See the GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Jay/Condor/Swift. If not, see
    <https://www.gnu.org/licenses/>.

*/


package ucl.service.zip.jaxws;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.0
 * Fri Aug 24 12:26:10 BST 2018
 * Generated source version: 2.4.0
 */

@XmlRootElement(name = "catchjob", namespace = "http://zip.service.ucl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "catchjob", namespace = "http://zip.service.ucl/")

public class Catchjob {

    @XmlElement(name = "basket")
    private java.lang.String basket;

    public java.lang.String getBasket() {
        return this.basket;
    }

    public void setBasket(java.lang.String newBasket)  {
        this.basket = newBasket;
    }

    @XmlElement(name = "type")
    private java.lang.String type;

    public java.lang.String getType() {
        return this.type;
    }

    public void setType(java.lang.String newType)  {
        this.type = newType;
    }

}

