/*
    This file is part of Jay/Condor/Swift.

    Jay/Condor/Swift is free software: you can redistribute it and/or
    modify it under the terms of the GNU General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    Jay/Condor/Swift is distributed in the hope that it will be
    useful, but WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
    PURPOSE. See the GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Jay/Condor/Swift. If not, see
    <https://www.gnu.org/licenses/>.

*/

package ucl.service.zip.jaxws;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

import jakarta.activation.DataHandler;

/**
 * This class was generated by Apache CXF 2.4.0
 * Fri Aug 24 12:26:11 BST 2018
 * Generated source version: 2.4.0
 */

@XmlRootElement(name = "catchjobResponse", namespace = "http://zip.service.ucl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "catchjobResponse", namespace = "http://zip.service.ucl/")

public class CatchjobResponse {

    @XmlElement(name = "return")
    private DataHandler _return;

    public DataHandler getReturn() {
        return this._return;
    }

    public void setReturn(DataHandler new_return)  {
        this._return = new_return;
    }

}

