<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  
  <parent>
    <groupId>ucl.service</groupId>
    <artifactId>aves-parent</artifactId>
    <version>1.0.0</version>
  </parent>

  <artifactId>Jay</artifactId>
  <packaging>war</packaging>
  <name>Jay</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>

    <!-- Dependency on the shared CommonBirds module -->
    <dependency>
      <groupId>ucl.service</groupId>
      <artifactId>CommonBirds</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- Add other dependencies specific to Jay here -->


    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <finalName>Jay</finalName>
  </build>
</project>
