<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  
  <parent>
    <groupId>ucl.service</groupId>
    <artifactId>aves-parent</artifactId>
    <version>1.0.0</version>
  </parent>

  <artifactId>Jay</artifactId>
  <packaging>war</packaging>
  <name>Jay</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>

    <!-- Dependency on the shared CommonBirds module -->
    <dependency>
      <groupId>ucl.service</groupId>
      <artifactId>CommonBirds</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- Add other dependencies specific to Jay here -->


    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <finalName>Jay</finalName>
    <plugins>
      <plugin>
	<artifactId>maven-war-plugin</artifactId>
	<version>3.4.0</version>
	<configuration>
          <webResources>
	    <!-- Copy any top level Web files -->
            <resource>
              <directory>../CommonBirds/src/main/resources/web/html</directory>
              <targetPath>/</targetPath>
	      <!-- Things not to copy ... -->
	      <excludes>
		<!-- Files Jay overrides with its own versions -->
		<exclude>index.html</exclude>
		<exclude>DARForm.html</exclude>
		<exclude>MockUpJay.html</exclude>
              </excludes>
            </resource>
	    
            <!-- Copy templates from CommonBirds -->
            <resource>
              <directory>../CommonBirds/src/main/resources/templates</directory>
              <targetPath>/templates</targetPath>
            </resource>
            
            <!-- Copy transactions from CommonBirds -->
            <resource>
              <directory>../CommonBirds/src/main/resources/web/transactions</directory>
              <targetPath>/transactions</targetPath>
            </resource>

            <!-- Copy reports from CommonBirds -->
            <resource>
              <directory>../CommonBirds/src/main/resources/web/reports</directory>
              <targetPath>/reports</targetPath>
            </resource>

            <!-- Copy CSS files -->
            <resource>
              <directory>../CommonBirds/src/main/resources/web/css</directory>
              <targetPath>/</targetPath>
              <includes>
		<include>**/*.css</include>
              </includes>
            </resource>
            
            <!-- Copy JavaScript files -->
            <resource>
              <directory>../CommonBirds/src/main/resources/web/js</directory>
              <targetPath>/</targetPath>
              <includes>
		<include>**/*.js</include>
              </includes>
            </resource>

	  </webResources>
	</configuration>
      </plugin>
    </plugins>
  </build>
</project>
