# Properties file for smtp.properties as part of SWIFT20
mailHost=isd-smtp.ucl.ac.uk
# Change this to something which is relevant for the SWIFT deployment, eg, a DSG alias
mailSender=mrclha.swiftinfo@ucl.ac.uk
# Change this to something which is relevant for the SWIFT deployment, eg, TEST or PROD
sysVersion=rook
