# Authors: Phil Curran, SST
# All software released under GNU GPL
# This file is <App Name>/src/mrc/wdap/user/system.properties
# Deployment Environment
# Note that installRoot is the context path not the physical file location, beware!!
#
# Whatever you do, DO NOT PUT QUOTES round the file paths documentDir, etc.!!!!!
#
installServer=mrc-swan01.ad.ucl.ac.uk
installRoot=PyJobService # Used in Scramble.java line 136
swtFileServicePort=8984 # Not Used !!!!!
# python path to save scripts - path that can be read from windows
pyLogFile=/xnat/san/SST/baskets/BasketBuilding.log # Not Used
pyWinPath=//mrc-swan01.ad.ucl.ac.uk/SST/baskets # Not Used
# path to save dataset - path that can be read from postgres
pyLinPath=/xnat/san/SST/baskets # Not Used
# Database Parameters for MySQL and PostgreSQL
pyMyDriver={MySQL ODBC 5.3 Unicode Driver}; # Not Used
pyMyServer=localhost # Not Used
pyMyDBase=rook # Not Used 
pyMyDBaseScram=scrambling # Not Used
pyMyUID=DBA # Not Used
pyMyPwd=!$75R<k19> # Not Used
pyPgDBase=nshd # Not Used
pyPgUID=postgres # Not Used
# Change pyPgServer in production version!!!!
pyPgServer=mrc-swan01.ad.ucl.ac.uk # Not Used
pyPgPwd=m1a9r4c6h # Not Used
pyPgZIPServicePort=8984 # Not Used
pyTrolleyLimit=3 # Not Used
# This one is mentioned in Boomerang but missing here?
pyScriptPath=/opt/swift/bash # Not Used
