# Authors: Phil Curran
# 
# This file is .../zipservice.properties
# 
# Whatever you do, DO NOT PUT QUOTES round the file paths documentDir, etc.!!!!!
#
service_name=http://mrc-swan01.ad.ucl.ac.uk:8984/PyJobService/services/BoomerangPort
# Above gets used by service users, the rest are for PyJobService use
installRoot=PyJobService # Used in Scramble.java line 136
# path to save dataset - path that can be read from postgres
pyLinPath=/xnat/san/SST/baskets 
# Database Parameters for MySQL and PostgreSQL
pyPgZIPServicePort=8984
# The path to all the NSHD bash scripts on swan/swandv01
pyScriptPath=/opt/swift/bash
# path to save dataset - path that can be read from postgres
# Suffix for basket building
pyBuildSuf=raw
# Suffix for scrambling
pyScramSuf=scrambled
