# Authors: Phil Curran, SST
# Copyright (c) 2007-2018 UCL/Medical Research Council 
# ALL RIGHTS RESERVED
# This file is SWIFT12/src/mrc/wdap/user/system.properties
# Deployment Environment
# Note that installRoot is the context path not the physical file location, beware!!
# Not sure which is the master file.  Commenting out this one for a new build
#
# Whatever you do, DO NOT PUT QUOTES round the file paths documentDir, etc.!!!!!
#
installRoot=SWIFT20/rook
#documentDir=C:\\apache-tomcat-6.0.36\\webapps\\SWIFT12\\rook\\Documents
#dsgDownloadDir=C:\\apache-tomcat-6.0.36\\webapps\\SWIFT12\\rook\\download
#dsgUploadDir=C:\\apache-tomcat-6.0.36\\webapps\\SWIFT12\\rook\\upload
#pdfDir=C:\\apache-tomcat-6.0.36\\webapps\\SWIFT12\\rook\\PDF
# Here are the settings for SWIFT on Perseus/Pegasus
documentDir=webapps/SWIFT20/rook/Documents
dsgDownloadDir=webapps/SWIFT20/rook/download
dsgUploadDir=webapps/SWIFT20/rook/upload
dsgTrolleyLimit=3
dsgBasketLimit=300
pdfDir=webapps/SWIFT20/PDF
xforms=webapps/SWIFT20/rook/FORMS
xstyle=webapps/SWIFT20/XNT-Sum.xsl
swtFileServicePort=8984
# python path to save scripts - path that can be read from windows
pyWinPath=//swan/SST/baskets
# path to save dataset - path that can be read from postgres
pyLinPath=/xnat/san/SST/baskets
# Database Parameters for MySQL and PostgreSQL
pyMyDriver={MySQL ODBC 5.3 Unicode Driver};
pyMyServer=Kiwi.MRCEuston.local;
pyMyDBase=swift_prod_10;
pyMyDBaseScram=scrambling;
pyMyUID=root;
pyMyPwd=m1a9r4c6h;
pyPgDBase=nshd
pyPgUID=postgres
# Change pyPgServer in production version!!!!
pyPgServer=swantest.MRCEuston.local
pyPgPwd=m1a9r4c6h
pyPgZIPServicePort=8984
pyTrolleyLimit=3
